config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctors do 
    resources :appointments, only: [:index, :new]
  end
  resources :patients do 
    resources :doctors, only: [:index]
    resources :appointments, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
    get 'sign_in' => 'users/sessions#new'
    get 'sign_up' => 'users/registrations#new'
    get 'signup_success' => 'users/registrations#signup_success'
    get 'users/profile' => 'users/registrations#profile',
        :as => 'user_profile_settings'
  end
  root 'patients#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments
  has_many :doctors, through: :appointments
  
  validates :name, presence: true, uniqueness: {scope: :user_id}
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index 
    @patients = current_user.patients
  end

  def show 
    
  end

  def new 
    @patient = Patient.new
  end 

  def create 
    @patient = current_user.patients.build(patient_params)
    if @patient.save 
      redirect_to patient_path(@patient)
    else 
      render :new
    end
  end 

  def edit 

  end 

  def update 
    if @patient.update(patient_params)
      redirect_to patient_path(@patient)
    else 
      render :edit
    end
  end 
  
  def destroy 
    @patient.destroy 
    redirect_to patients_path
  end

  private 

  def set_patient 
    @patient = current_user.patients.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= show_errors_for(patient) %>
<%= form_for patient do |f| %>
  <p>
    <%= f.label :name, "Add your patient's name" %><br/>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>
<%= render partial: 'form', locals: { patient: @patient }%>

app/views/patients/index.html.erb
<div class="p-3 mb-2 bg-secondary text-white">Patients List</div>

<%= link_to 'Add Patient', new_patient_path , :class => 'btn btn-primary'%>
<% @patients.each do |patient| %>
  <p><%= link_to patient.name, patient_path(patient) %></p>
<% end %>

app/views/patients/new.html.erb
<h1>New Patient</h1>
<%= render partial: 'form', locals: { patient: @patient }%>

app/views/patients/show.html.erb
<h1><%= @patient.name %></h1>
<p><%= link_to "Book appointment for #{@patient.name} ", new_patient_appointment_path(@patient) %></p>
<p><%= link_to "#{@patient.name}'s appointments", patient_appointments_path(@patient) %></p>
<p><%= link_to  "Edit Patient", edit_patient_path(@patient) %>
<%= form_tag(patient_path(@patient), method: :delete) do%>
<%= submit_tag "Delete Patient" %>
<% end %>
</p>