config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctors do 
    resources :appointments, only: [:index, :new]
  end
  resources :patients do 
    resources :doctors, only: [:index]
    resources :appointments, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
    get 'sign_in' => 'users/sessions#new'
    get 'sign_up' => 'users/registrations#new'
    get 'signup_success' => 'users/registrations#signup_success'
    get 'users/profile' => 'users/registrations#profile',
        :as => 'user_profile_settings'
  end
  root 'patients#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
  validates :name, :phone_number, :specializations, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index 
    @doctors = Doctor.all
  end 

  def show 

  end 

  def new 
    @doctor = Doctor.new
  end 

  def create 
    @doctor = Doctor.new(doctor_params)
    if @doctor.save 
      redirect_to doctor_path(@doctor)
    else
      render :new 
    end
  end 


  private 

  def set_doctor 
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :phone_number, :specializations)
  end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/index.html.erb
<section class="vh-100 gradient-custom " >
  <div class="container py-5 ">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7 ">
        <div class="card shadow-2-strong card-registration ,  bg-primary text-white" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5 ">
            <form>
<div class="field">
      <div class="row">
        <div class="col-md-4 offset-4 , actions ">
<center> <h1>Doctors</h1> </center>
<%= link_to 'Add Doctor', new_doctor_path , :class => 'text-white' %>
<% @doctors.each do |doctor| %>
  <p><%= link_to doctor.name, doctor_path(doctor) , :class => 'text-white'%></p>
<% end %>

 </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/doctors/new.html.erb
<section class="vh-100" style="background-color: #2779e2;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-9">

        <h1 class="text-white mb-4">Add Doctor</h1>
        <%= show_errors_for(@doctor) %>
        <%= form_for @doctor do |f| %>

        <div class="card" style="border-radius: 15px;">
          <div class="card-body">

            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">
                <h6 class="mb-0">Full name</h6>
              </div>
              <div class="col-md-9 pe-5">
                <%= f.text_field :name  , class: "form-control form-control-lg"%>
              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Phone Number</h6>

              </div>
              <div class="col-md-9 pe-5">

                <%= f.text_field :phone_number  , class: "form-control form-control-lg"%>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Specializations</h6>

              </div>
              <div class="col-md-9 pe-5">
          <%= f.text_field :specializations  , class: "form-control form-control-lg"%>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Upload CV</h6>

              </div>
              <div class="col-md-9 pe-5">

                <input class="form-control form-control-lg" id="formFileLg" type="file" />
                <div class="small text-muted mt-2">Upload your CV/Resume or any other relevant file. Max file
                  size 50 MB</div>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="px-5 py-4">
                <%= f.submit %>
                <% end %>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>

app/views/doctors/show.html.erb
<section class="vh-100 gradient-custom " >
  <div class="container py-5 ">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration , bg-dark text-white" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <form>
<div class="field">
      <div class="row">
        <div class="col-md-10  , actions ">
<h1>Dr. <%= @doctor.name %></h1>
<h1>Specializations <%= @doctor.specializations%></h1>

<div class="text-warning">
<p><%= link_to  "Book with #{@doctor.name}", new_doctor_appointment_path(@doctor) , :class => "text-warning"  %></p>
<p><%= link_to  "#{@doctor.name}'s appointments", doctor_appointments_path(@doctor) , :class => "text-warning"  %></p>
</div>
</div>
</div>
</div>

 </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>