config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctors do 
    resources :appointments, only: [:index, :new]
  end
  resources :patients do 
    resources :doctors, only: [:index]
    resources :appointments, only: [:index, :new]
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } do
    get 'sign_in' => 'users/sessions#new'
    get 'sign_up' => 'users/registrations#new'
    get 'signup_success' => 'users/registrations#signup_success'
    get 'users/profile' => 'users/registrations#profile',
        :as => 'user_profile_settings'
  end
  root 'patients#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient

  validates :start_time, :end_time, :location, presence: true
  validate :doctor_double_booked, :patient_double_booked, if: :starts_before_it_ends?
  validate :ends_after_it_starts
  # what does it mean for a double booking to exist. What conditions mean that a doctor or a patient is double booked?
  # if the doctor has any appointment that:
  #   starts in the middle of this appointment (other_appt.start_time < this_appt.start_time && thor ends in the middle of this appointment then it's a double booking on the doctor's part
  # other_start < this_end && this_end < other_end # this means that this appointment ends in the middle of an existing appointment.

  # other_start < this_start && this_start < other_end means that this appointment starts in the middle of an existing appointment
  def doctor_double_booked
    this_start = self.start_time
    this_end = self.end_time
    conflict = doctor.appointments.any? do |appointment|
      other_start = appointment.start_time 
      other_end = appointment.end_time
      other_start < this_end && this_end < other_end || other_start < this_start && this_start < other_end
    end
    if conflict
      errors.add(:doctor, 'has a conflicting appointment')
    end
  end

  def patient_double_booked
    this_start = self.start_time
    this_end = self.end_time
    conflict = patient.appointments.any? do |appointment|
      other_start = appointment.start_time 
      other_end = appointment.end_time
      other_start < this_end && this_end < other_end || other_start < this_start && this_start < other_end
    end
    if conflict
      errors.add(:patient, 'has a conflicting appointment')
    end
  end

  def ends_after_it_starts
    if !starts_before_it_ends?
      errors.add(:start_time, 'must be before the end time')
    end
  end

  def starts_before_it_ends?
    start_time < end_time
  end

  def doctor_name 
    self.doctor.name
  end

  def patient_name 
    self.patient.name
  end

  #scope method that returns all appointments that belong to a particular doctor.
  def self.by_doctor(doctor)
    where(doctor_id: doctor.id)
  end

  def self.upcoming
    where("start_time > ?", Time.now)
  end

  def self.past 
    where("start_time < ?", Time.now)
  end

  def self.most_recent
    order(start_time: :desc)
  end

  def self.longest_ago
    order(start_time: :asc)
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index 
    @patient = current_user.patients.find_by_id(params[:patient_id])
    @doctor = Doctor.find_by_id(params[:doctor_id])
    if @patient
      @appointments = @patient.appointments
    elsif @doctor 
      @appointments = current_user.appointments.by_doctor(@doctor)
    else
      @appointments = current_user.appointments
    end
    filter_options
  end

  def show 

  end 

  def new 
    @patient = current_user.patients.find_by_id(params[:patient_id])
    @doctor = Doctor.find_by_id(params[:doctor_id])
    if @patient
      @appointment = @patient.appointments.build
    elsif @doctor 
      @appointment = @doctor.appointments.build
    else
      @appointment = Appointment.new
    end
  end

  def create 
    @appointment = Appointment.new(appointment_params)
    if @appointment.save 
      redirect_to appointment_path(@appointment)
    else 
      render :new
    end
  end

  def edit 
    
  end 

  def update 
    if @appointment.update(appointment_params)
      redirect_to appointment_path(@appointment)
    else
      render :edit
    end
  end 

  def destroy 
    @appointment.destroy 
    redirect_to appointments_path
  end

  private 

  def set_appointment 
    @appointment = current_user.appointments.find(params[:id])
  end

  def filter_options 
    if params[:filter_by_time] == "upcoming"
      @appointments = @appointments.upcoming
    elsif params[:filter_by_time] == "past"
      @appointments = @appointments.past
    end
    if params[:sort] == "most_recent"
      @appointments = @appointments.most_recent
    elsif params[:sort] == "longest_ago" 
      @appointments = @appointments.longest_ago
    end
  end

  def appointment_params
    params.require(:appointment).permit(:location, :start_time, :end_time, :doctor_id, :patient_id)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<section class="vh-100 gradient-custom " >
  <div class="container py-5 ">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration , bg-secondary text-white" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <form>

      <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4 , actions ">

<%= show_errors_for(appointment) %>
<%= form_for appointment do |f| %>
  <p>
    <% if appointment.patient_id %>
      <%= f.label :patient_id, "Patient" %>
      <%= f.hidden_field :patient_id %>
      <%= appointment.patient.name %>
    <% else %>

      <%= f.label :patient_id, "patient" %>
      <%= f.collection_select :patient_id, current_user.patients, :id, :name %>
    <% end %>
  </p>
  <p>

  <% if appointment.doctor_id %>
    <%= f.label :doctor_id, "Doctor" %>
    <%= f.hidden_field :doctor_id %>
    <%= appointment.doctor.name %>
  <% else %>

    <%= f.label :doctor_id, "Doctor" %>
    <%= f.collection_select :doctor_id, Doctor.all, :id, :name ,class:  "form-control" %>
  <% end %>
  </p>
</div>
</div>
</div>

  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4 , actions ">
 <p>
    <%= f.label :location %>
    <%= f.text_field :location ,class:  "form-control" %>
  </p>
        </div>
      </div>
</div>



  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4 , actions ">
          <%= f.label :start_time %>
    <%= f.datetime_field :start_time ,class:  "form-control"%>
        </div>
      </div>
</div>


  <div class="field">
      <div class="row">
        <div class="col-md-4 offset-4 , actions ">
      <%= f.label :end_time %>
    <%= f.datetime_field :end_time ,class:  "form-control"%>
        </div>
      </div>
</div> <br>


<div class="field">
      <div class="row">
        <div class="col-md-4 offset-4 , actions ">
          <%= f.submit "Create Appointment", :class => 'btn btn-primary' %>
        </div>
      </div>
  <% end %>
</div>
 </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/appointments/edit.html.erb
<center><h1>Edit Appointment</h1></center>
<%= render partial: 'form', locals: { appointment: @appointment} %>

app/views/appointments/index.html.erb
<center> <h1>Appointments</h1> </center>
<button><%= link_to  "Add Appointment", new_appointment_path %></button>
<%= form_tag(appointments_path, method: 'get') do %>
  <label for="filter_by_time">Filter By Time</label>
  <select name="filter_by_time">
    <option <%= 'selected' if params[:filter_by_time] == '' %> value="">All</option>
    <option <%= 'selected' if params[:filter_by_time] == 'past' %> value="past">Past</option>
    <option <%= 'selected' if params[:filter_by_time] == 'upcoming' %> value="upcoming">Upcoming</option>
  </select>
  <label for="sort">Sort</label>
  <select name="sort">
    <option <%= 'selected' if params[:sort] == '' %> value="">None</option>
    <option <%= 'selected' if params[:sort] == 'most_recent' %> value="most_recent">Most Recent</option>
    <option <%= 'selected' if params[:sort] == 'longest_ago' %> value="longest_ago">Longest Ago</option>
  </select>
  <%= submit_tag 'Filter Results' %>
<% end %>
<% @appointments.each do |appointment| %>
  <p>
    <%= link_to appointment.patient_name, patient_path(appointment.patient) %> has an appointment at <%= link_to appointment.start_time.strftime('%b %e, %l:%M %p'), appointment_path(appointment) %> with <%= link_to appointment.doctor_name, doctor_path(appointment.doctor) %>
  </p>
<% end %>

app/views/appointments/new.html.erb
<center> <h1>New Appointment</h1> </center>
<%= render partial: 'form', locals: { appointment: @appointment} %>

app/views/appointments/show.html.erb
<center> <h1>Appointment Details</h1></center>
<p>Patient: <%= link_to @appointment.patient_name, patient_path(@appointment.patient) %></p>
<p>Doctor: <%= link_to @appointment.doctor_name, doctor_path(@appointment.doctor) %></p>
<p>Location: <%= @appointment.location %></p>
<p>Start Time: <%= @appointment.start_time.strftime('%b %e, %l:%M %p') %></p>
<p>End Time: <%= @appointment.end_time.strftime('%b %e, %l:%M %p') %></p>
<%= link_to "Edit Appointment", edit_appointment_path(@appointment) %>
<%= form_tag(appointment_path(@appointment), method: :delete, style: 'display: inline-block;') do %>
  <%= submit_tag "Delete Appointment" %>
<% end %>